apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: py-psql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: PSQL_HOST
              value: {{ .Values.psql.host | quote }}
            - name: PSQL_PORT
              value: {{ .Values.psql.password | quote }}
            - name: PSQL_USERNAME
              value: {{ .Values.psql.username | quote }}
            - name: PSQL_PASSWORD
              value: {{ toYaml .Values.psql.host | indent 16 }}
            - name: PSQL_DATABASE
              value: {{ .Values.psql.database | quote }}
      imagePullSecrets:
        - name: ghcr-secret
