replicaCount: 1

image:
  repository: ghcr.io/paul-gsd/helm-py-psql/py-psql
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

containerPort: 8080

psql:
  host: test-psql
  port: 5432
  username:
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: my
  password: asdf
  database: test
