replicaCount: 1

image:
  repository: ghcr.io/paul-gsd/helm-py-psql/py-psql
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

containerPort: 8080

psql:
  host:
  port:
  username:
  password:
  database:
